// -*- C++ -*- generated by wxGlade 0.6.3 on Fri Feb 25 18:55:11 2011

#include <wx/wx.h>
#include <wx/image.h>

#ifndef BUDGETFRAME_H
#define BUDGETFRAME_H

// begin wxGlade: ::dependencies
#include <wx/listctrl.h>
// end wxGlade

#include "Budget.h"
#include "VersionControl.h"

// begin wxGlade: ::extracode

// end wxGlade


class BudgetFrame: public wxFrame {
public:
    // begin wxGlade: BudgetFrame::ids
    // end wxGlade

    BudgetFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: BudgetFrame::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: BudgetFrame::attributes
    wxMenuBar* menubar;
    wxListCtrl* categoryList;
    wxStaticText* totalLabel;
    wxPanel* panel_1;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnNewPressed(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnOpenPressed(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnCombinePressed(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnSavePressed(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnSaveAsPressed(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnExitPressed(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnUndoPressed(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnRedoPressed(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnAddPressed(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnRemovePressed(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnRenamePressed(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnViewPressed(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnExamplePressed(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnHelpPressed(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnAboutPressed(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnCategoryDeselected(wxListEvent &event); // wxGlade: <event_handler>
    virtual void OnCategorySelected(wxListEvent &event); // wxGlade: <event_handler>
    virtual void OnCategoryActivated(wxListEvent &event); // wxGlade: <event_handler>

private:
    void LoadBudget(Budget* budget);
    void UpdateBudget();
    void UpdateTitle();
    void UpdateCategoryList();
    void ResizeListColumns();

    VersionControl* _budget;
}; // wxGlade: end class


#endif // BUDGETFRAME_H
