// -*- C++ -*- generated by wxGlade 0.6.3 on Fri Feb 25 18:55:11 2011

#include <wx/wx.h>
#include <wx/image.h>

#ifndef CATEGORYDIALOG_H
#define CATEGORYDIALOG_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class CategoryDialog: public wxDialog {
public:
    // begin wxGlade: CategoryDialog::ids
    // end wxGlade

    CategoryDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: CategoryDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: CategoryDialog::attributes
    wxStaticText* label_1;
    wxTextCtrl* nameTextCtrl;
    wxStaticText* label_2;
    wxTextCtrl* amountTextCtrl;
    wxStaticText* totalLabel;
    wxButton* cancelButton;
    wxButton* okButton;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnOkPressed(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnAmountChanged(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnCancelPressed(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // CATEGORYDIALOG_H
