// -*- C++ -*- generated by wxGlade 0.6.3 on Fri Feb 25 18:55:11 2011

#include "CategoryDialog.h"

// begin wxGlade: ::extracode

// end wxGlade


CategoryDialog::CategoryDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE)
{
    // begin wxGlade: CategoryDialog::CategoryDialog
    label_1 = new wxStaticText(this, wxID_ANY, wxT("Name:"));
    nameTextCtrl = new wxTextCtrl(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_PROCESS_ENTER);
    label_2 = new wxStaticText(this, wxID_ANY, wxT("Initial Amount:"), wxDefaultPosition, wxDefaultSize, wxALIGN_RIGHT);
    amountTextCtrl = new wxTextCtrl(this, wxID_ANY, wxT("0.00"), wxDefaultPosition, wxDefaultSize, wxTE_PROCESS_ENTER|wxTE_RIGHT);
    totalLabel = new wxStaticText(this, wxID_ANY, wxT("Budget Total: 0.00"));
    cancelButton = new wxButton(this, wxID_ANY, wxT("&Cancel"));
    okButton = new wxButton(this, wxID_ANY, wxT("&Add Category"));

    set_properties();
    do_layout();
    // end wxGlade
}


BEGIN_EVENT_TABLE(CategoryDialog, wxDialog)
    // begin wxGlade: CategoryDialog::event_table
    EVT_TEXT_ENTER(wxID_ANY, CategoryDialog::OnOkPressed)
    EVT_TEXT_ENTER(wxID_ANY, CategoryDialog::OnOkPressed)
    EVT_TEXT(wxID_ANY, CategoryDialog::OnAmountChanged)
    EVT_BUTTON(wxID_ANY, CategoryDialog::OnCancelPressed)
    EVT_BUTTON(wxID_ANY, CategoryDialog::OnOkPressed)
    // end wxGlade
END_EVENT_TABLE();


void CategoryDialog::OnOkPressed(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (CategoryDialog::OnOkPressed) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


void CategoryDialog::OnAmountChanged(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (CategoryDialog::OnAmountChanged) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


void CategoryDialog::OnCancelPressed(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (CategoryDialog::OnCancelPressed) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


// wxGlade: add CategoryDialog event handlers


void CategoryDialog::set_properties()
{
    // begin wxGlade: CategoryDialog::set_properties
    SetTitle(wxT("Add Category"));
    // end wxGlade
}


void CategoryDialog::do_layout()
{
    // begin wxGlade: CategoryDialog::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* buttonSizer = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* okSizer = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* cancelSizer = new wxBoxSizer(wxVERTICAL);
    sizer_1->Add(label_1, 0, wxLEFT|wxRIGHT|wxTOP, 10);
    sizer_1->Add(nameTextCtrl, 0, wxLEFT|wxRIGHT|wxEXPAND, 10);
    sizer_1->Add(label_2, 0, wxLEFT|wxRIGHT|wxTOP, 10);
    sizer_1->Add(amountTextCtrl, 0, wxLEFT|wxRIGHT|wxEXPAND, 10);
    sizer_1->Add(totalLabel, 0, wxALL|wxALIGN_RIGHT, 10);
    cancelSizer->Add(cancelButton, 0, wxALL, 10);
    buttonSizer->Add(cancelSizer, 1, wxALIGN_BOTTOM, 0);
    okSizer->Add(okButton, 0, wxALL|wxALIGN_RIGHT, 10);
    buttonSizer->Add(okSizer, 1, wxALIGN_BOTTOM, 0);
    sizer_1->Add(buttonSizer, 1, wxEXPAND, 0);
    SetSizer(sizer_1);
    sizer_1->Fit(this);
    Layout();
    Centre();
    // end wxGlade
}

