// -*- C++ -*- generated by wxGlade 0.6.3 on Fri Feb 25 18:55:11 2011

#include <wx/wx.h>
#include <wx/image.h>

#ifndef CATEGORYFRAME_H
#define CATEGORYFRAME_H

// begin wxGlade: ::dependencies
#include <wx/listctrl.h>
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class CategoryFrame: public wxFrame {
public:
    // begin wxGlade: CategoryFrame::ids
    // end wxGlade

    CategoryFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: CategoryFrame::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: CategoryFrame::attributes
    wxMenuBar* menubar;
    wxListCtrl* transactionList;
    wxStaticText* totalLabel;
    wxPanel* panel_1;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnClosePressed(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnAddPressed(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnRemovePressed(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnEditPressed(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnDeletePressed(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnTransactionDeselected(wxListEvent &event); // wxGlade: <event_handler>
    virtual void OnTransactionSelected(wxListEvent &event); // wxGlade: <event_handler>
    virtual void OnTransactionActivated(wxListEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // CATEGORYFRAME_H
