// -*- C++ -*- generated by wxGlade 0.6.3 on Fri Feb 25 18:55:11 2011

#include "HelpFrame.h"

// begin wxGlade: ::extracode

// end wxGlade


HelpFrame::HelpFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxFrame(parent, id, title, pos, size, wxDEFAULT_FRAME_STYLE)
{
    // begin wxGlade: HelpFrame::HelpFrame

    set_properties();
    do_layout();
    // end wxGlade
}


void HelpFrame::set_properties()
{
    // begin wxGlade: HelpFrame::set_properties
    SetTitle(wxT("DivvyUp Tutorial"));
    SetSize(wxSize(600, 500));
    // end wxGlade
}


void HelpFrame::do_layout()
{
    // begin wxGlade: HelpFrame::do_layout
    Layout();
    Centre();
    // end wxGlade
}

