// -*- C++ -*- generated by wxGlade 0.6.3 on Fri Feb 25 18:55:11 2011

#include <wx/wx.h>
#include <wx/image.h>

#ifndef HELPFRAME_H
#define HELPFRAME_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class HelpFrame: public wxFrame {
public:
    // begin wxGlade: HelpFrame::ids
    // end wxGlade

    HelpFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: HelpFrame::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: HelpFrame::attributes
    // end wxGlade
}; // wxGlade: end class


#endif // HELPFRAME_H
