// -*- C++ -*- generated by wxGlade 0.6.3 on Fri Feb 25 18:55:11 2011

#include <wx/wx.h>
#include <wx/image.h>
#include "BudgetFrame.h"



class DivvyUp: public wxApp {
public:
    bool OnInit();
};

IMPLEMENT_APP(DivvyUp)

bool DivvyUp::OnInit()
{
    wxInitAllImageHandlers();
    BudgetFrame* budgetFrame = new BudgetFrame(NULL, wxID_ANY, wxEmptyString);
    SetTopWindow(budgetFrame);
    budgetFrame->Show();
    return true;
}
