// -*- C++ -*- generated by wxGlade 0.6.3 on Fri Feb 25 18:55:11 2011

#include "RenameDialog.h"

// begin wxGlade: ::extracode

// end wxGlade


RenameDialog::RenameDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE)
{
    // begin wxGlade: RenameDialog::RenameDialog
    nameLabel = new wxStaticText(this, wxID_ANY, wxT("Rename Category to:"));
    nameTextCtrl = new wxTextCtrl(this, wxID_ANY, wxT("Category"), wxDefaultPosition, wxDefaultSize, wxTE_PROCESS_ENTER);
    cancelButton = new wxButton(this, wxID_ANY, wxT("&Cancel"));
    okButton = new wxButton(this, wxID_ANY, wxT("&Rename"));

    set_properties();
    do_layout();
    // end wxGlade
}


BEGIN_EVENT_TABLE(RenameDialog, wxDialog)
    // begin wxGlade: RenameDialog::event_table
    EVT_TEXT_ENTER(wxID_ANY, RenameDialog::OnOkPressed)
    EVT_BUTTON(wxID_ANY, RenameDialog::OnCancelPressed)
    EVT_BUTTON(wxID_ANY, RenameDialog::OnOkPressed)
    // end wxGlade
END_EVENT_TABLE();


void RenameDialog::OnOkPressed(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (RenameDialog::OnOkPressed) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


void RenameDialog::OnCancelPressed(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (RenameDialog::OnCancelPressed) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


// wxGlade: add RenameDialog event handlers


void RenameDialog::set_properties()
{
    // begin wxGlade: RenameDialog::set_properties
    SetTitle(wxT("Rename"));
    // end wxGlade
}


void RenameDialog::do_layout()
{
    // begin wxGlade: RenameDialog::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* buttonSizer = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* okSizer = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* cancelSizer = new wxBoxSizer(wxVERTICAL);
    sizer_1->Add(nameLabel, 0, wxLEFT|wxRIGHT|wxTOP, 10);
    sizer_1->Add(nameTextCtrl, 0, wxLEFT|wxRIGHT|wxEXPAND, 10);
    cancelSizer->Add(cancelButton, 0, wxALL, 10);
    buttonSizer->Add(cancelSizer, 1, wxALIGN_BOTTOM, 0);
    okSizer->Add(okButton, 0, wxALL|wxALIGN_RIGHT, 10);
    buttonSizer->Add(okSizer, 1, wxALIGN_BOTTOM, 0);
    sizer_1->Add(buttonSizer, 1, wxEXPAND, 0);
    SetSizer(sizer_1);
    sizer_1->Fit(this);
    Layout();
    // end wxGlade
}

