// -*- C++ -*- generated by wxGlade 0.6.3 on Fri Feb 25 18:55:11 2011

#include "TransactionDialog.h"

// begin wxGlade: ::extracode

// end wxGlade


TransactionDialog::TransactionDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE)
{
    // begin wxGlade: TransactionDialog::TransactionDialog
    categoryLabel = new wxStaticText(this, wxID_ANY, wxT("Add to Category:"));
    amountText = new wxTextCtrl(this, wxID_ANY, wxT("0.00"), wxDefaultPosition, wxDefaultSize, wxTE_PROCESS_ENTER|wxTE_RIGHT);
    label_1 = new wxStaticText(this, wxID_ANY, wxT("Reason:"));
    reasonText = new wxTextCtrl(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_PROCESS_ENTER|wxTE_RIGHT);
    label_2 = new wxStaticText(this, wxID_ANY, wxT("Date:"));
    datepicker = new wxDatePickerCtrl(this, wxID_ANY, wxDefaultDateTime, wxDefaultPosition, wxDefaultSize, wxDP_SHOWCENTURY);
    categoryTotalLabel = new wxStaticText(this, wxID_ANY, wxT("Category: 0.00"));
    budgetTotalLabel = new wxStaticText(this, wxID_ANY, wxT("Budget: 0.00"));
    cancelButton = new wxButton(this, wxID_ANY, wxT("&Cancel"));
    okButton = new wxButton(this, wxID_ANY, wxT("&Add"));

    set_properties();
    do_layout();
    // end wxGlade
}


BEGIN_EVENT_TABLE(TransactionDialog, wxDialog)
    // begin wxGlade: TransactionDialog::event_table
    EVT_TEXT_ENTER(wxID_ANY, TransactionDialog::OnOkPressed)
    EVT_TEXT(wxID_ANY, TransactionDialog::OnAmountChanged)
    EVT_TEXT_ENTER(wxID_ANY, TransactionDialog::OnOkPressed)
    EVT_BUTTON(wxID_ANY, TransactionDialog::OnCancelPressed)
    EVT_BUTTON(wxID_ANY, TransactionDialog::OnOkPressed)
    // end wxGlade
END_EVENT_TABLE();


void TransactionDialog::OnOkPressed(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (TransactionDialog::OnOkPressed) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


void TransactionDialog::OnAmountChanged(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (TransactionDialog::OnAmountChanged) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


void TransactionDialog::OnCancelPressed(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (TransactionDialog::OnCancelPressed) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


// wxGlade: add TransactionDialog event handlers


void TransactionDialog::set_properties()
{
    // begin wxGlade: TransactionDialog::set_properties
    SetTitle(wxT("Add to Category"));
    // end wxGlade
}


void TransactionDialog::do_layout()
{
    // begin wxGlade: TransactionDialog::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* buttonSizer = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* okSizer = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* cancelSizer = new wxBoxSizer(wxVERTICAL);
    sizer_1->Add(categoryLabel, 0, wxLEFT|wxRIGHT|wxTOP, 10);
    sizer_1->Add(amountText, 0, wxLEFT|wxRIGHT|wxEXPAND, 10);
    sizer_1->Add(label_1, 0, wxLEFT|wxRIGHT|wxTOP|wxALIGN_CENTER_VERTICAL, 10);
    sizer_1->Add(reasonText, 0, wxLEFT|wxRIGHT|wxEXPAND, 10);
    sizer_1->Add(label_2, 0, wxLEFT|wxRIGHT|wxTOP, 10);
    sizer_1->Add(datepicker, 0, wxLEFT|wxRIGHT|wxBOTTOM, 10);
    sizer_1->Add(categoryTotalLabel, 0, wxLEFT|wxRIGHT|wxALIGN_RIGHT, 10);
    sizer_1->Add(budgetTotalLabel, 0, wxLEFT|wxRIGHT|wxALIGN_RIGHT, 10);
    cancelSizer->Add(cancelButton, 0, wxALL, 10);
    buttonSizer->Add(cancelSizer, 1, wxALIGN_BOTTOM, 0);
    okSizer->Add(okButton, 0, wxALL|wxALIGN_RIGHT, 10);
    buttonSizer->Add(okSizer, 1, wxALIGN_BOTTOM, 0);
    sizer_1->Add(buttonSizer, 1, wxEXPAND, 0);
    SetSizer(sizer_1);
    sizer_1->Fit(this);
    Layout();
    // end wxGlade
}

