// -*- C++ -*- generated by wxGlade 0.6.3 on Fri Feb 25 18:55:11 2011

#include <wx/wx.h>
#include <wx/image.h>

#ifndef TRANSACTIONDIALOG_H
#define TRANSACTIONDIALOG_H

// begin wxGlade: ::dependencies
#include <wx/datectrl.h>
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class TransactionDialog: public wxDialog {
public:
    // begin wxGlade: TransactionDialog::ids
    // end wxGlade

    TransactionDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: TransactionDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: TransactionDialog::attributes
    wxStaticText* categoryLabel;
    wxTextCtrl* amountText;
    wxStaticText* label_1;
    wxTextCtrl* reasonText;
    wxStaticText* label_2;
    wxDatePickerCtrl* datepicker;
    wxStaticText* categoryTotalLabel;
    wxStaticText* budgetTotalLabel;
    wxButton* cancelButton;
    wxButton* okButton;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnOkPressed(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnAmountChanged(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnCancelPressed(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // TRANSACTIONDIALOG_H
